POST http://localhost:5122/users
Content-Type: application/json
Authorization: TestingTokenXYZ


{
  "name": "Alice Smith",
  "email": "alice.smith@example.com"
}

###

GET http://localhost:5122/users
Authorization: TestingTokenXYZ

###

GET http://localhost:5122/users/1
Authorization: TestingTokenXYZ

###

PUT http://localhost:5122/users/5
Content-Type: application/json
Authorization: TestingTokenXYZ

{
  "name": "Alice Johnson",
  "email": "alice.johnson@example.com"
}

###

DELETE http://localhost:5122/users/1
Authorization: TestingTokenXYZ

### Test with invalid token

DELETE http://localhost:5122/users/1
Authorization: TestingToken
